### ISSUE TITLE
I can't use Discord Together on my bot.

### ISSUE THREAD

**Issue by assenzostefano** [apurv-r/discord-together#11]
Hi ✋, I am creating **my own bot Discord** and I would like to add the ability to watch YouTube in voice, play Poker and many other things on Discord and by searching on Google I found [your library for Python](https://pypi.org/project/discord-together/).

I immediately realized that the example shown on the [README.md](https://github.com/apurv-r/discord-together#readme) is still with the old commands and not with the **slash commands** and uses **discord.py**, instead I am using [Nextcord](https://github.com/nextcord/nextcord).
I tried to readjust the example on my bot but it keeps asking me to put an option (Poker, YouTube, Chess etc ..).

My code:
```
import nextcord
import os
from dotenv import load_dotenv 
from nextcord import Interaction
from nextcord.ext import commands
from discord_together import DiscordTogether

load_dotenv()
intents = nextcord.Intents.default()
intents.members = True

client = commands.Bot(command_prefix = "!")
testServerId = 990250369265320008

#When bot turn on send message on console
@client.event
async def on_ready():
    print("The bot is ready!")

@client.slash_command(guild_ids= [testServerId])
async def play(interaction : Interaction):
    link = await DiscordTogether.create_link('990250369760260159', 'poker')
    await interaction.response.send_message(f"Click the blue link!\n{link}")

client.run(os.getenv("BOT_TOKEN"))
```
As you can see above I directly entered the Discord voice channel ID, and the activity I want to use, but it gives me this error:

![immagine](https://user-images.githubusercontent.com/68437687/182163778-47e87bf3-5adf-4e4d-a561-dd9bfb2cff7f.png)

How should i do? Thanks so much in advance for your help!

**Comment by apurv-r** [comment]
Hi Stephano,

Despite the examples in the README being for the regular prefix commands instead of slash commands, the coding is pretty much the same. What you're missing here is constructing a DiscordTogether object.

In the examples, I've created a bot variable in on_ready to store the DiscordTogether object. Shown below:
```py
@client.event
async def on_ready():
    client.togetherControl = await DiscordTogether("BOT_TOKEN_HERE")
```

After you've done this, you need to use this newly created bot variable to create the link. So using the example you gave, it would be something like:
```py
@client.slash_command(guild_ids= [testServerId])
async def play(interaction : Interaction):
    link = await client.togetherControl.create_link('990250369760260159', 'poker')
    await interaction.response.send_message(f"Click the blue link!\n{link}")
```

It should now work. Do let me know if it does, if not, head on over to my discord [support server](https://discord.com/invite/2fbyXn2hJV) and I can help you there further.

Regards,

**Comment by assenzostefano** [comment]
Now it works, thanks a lot for your help 😄
